import { StyleSheet } from 'react-native';
import colors from 'src/constants/colors';
import { fonts } from 'src/constants/fonts';

export default StyleSheet.create({
  topContainer: {
    paddingVertical: 20,
    borderBottomEndRadius: 60,
    overflow: 'hidden',
    paddingBottom: 30,
  },
  imageStyle: {
    height: 110,
    width: 110,
    borderRadius: 110,
    alignSelf: 'center',
  },
  name: {
    fontFamily: fonts.regular,
    fontWeight: '400',
    fontSize: 20,
    lineHeight: 24,
    textAlign: 'center',
    color: colors.defaultWhite,
    // marginLeft: 20,
    marginTop: 10,
    textTransform: 'capitalize',
  },
  email: {
    fontFamily: fonts.regular,
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 20,
    textAlign: 'center',
    color: colors.defaultWhite,
    // marginLeft: 20,
    marginTop: 10,
  },
  box: {
    backgroundColor: colors.whiteOpacity,
    padding: 10,
    margin: 2.5,
    flex: 1,
    borderRadius: 5,
    // height: 70,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  box2: {
    backgroundColor: colors.whiteOpacity,
    margin: 2.5,
    flex: 1,
    borderRadius: 5,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    // padding: 10
  },
  boxText: {
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 14,
    textAlign: 'center',
    color: colors.defaultWhite,
    textTransform: 'capitalize',
  },
  bioText: {
    fontFamily: fonts.regular,
    fontWeight: '300',
    fontSize: 15,
    lineHeight: 18,
    color: colors.defaultBlack,
  },
  iconWrapper: {
    backgroundColor: colors.regentBlue,
    borderRadius: 50,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    right: 15,
    top: -15,
  },
  heading: {
    fontSize: 18,
    lineHeight: 21,
    textAlign: 'center',
    fontFamily: fonts.regular,
    color: colors.defaultBlack,
  },
  description: {
    fontSize: 15,
    lineHeight: 18,
    // textAlign: 'center',
    fontFamily: fonts.regular,
    color: colors.lightBlack,
    marginTop: 20,
  },
});
