import { StyleSheet } from 'react-native';
import colors from 'src/constants/colors';
import { fonts } from 'src/constants/fonts';

export default StyleSheet.create({
  container: {
    backgroundColor: colors.defaultWhite,
    flexDirection: 'row',
    height: 55,
    borderRadius: 10,
    marginHorizontal: 20,
    paddingHorizontal: 20,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  text: {
    fontFamily: fonts.regular,
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '400',
    color: colors.defaultBlack,
    marginLeft: 15,
    flex: 1,
  },
  delete: {
    backgroundColor: colors.red,
    // height: 55,
    flex: 1,
    width: 105,
    alignSelf: 'flex-end',
    alignItems: 'flex-end',
    justifyContent: 'center',
    // borderTopRightRadius: 10,
    // borderBottomRightRadius: 10,
    borderRadius: 10,
    marginRight: 20,
    paddingRight: 15,
    marginBottom: 10,
    // position: 'absolute',
    // right: 0,
    // width: 75,
    // top: 0,
    // bottom: 0,
  },
  removeText: {
    fontFamily: fonts.regular,
    fontSize: 13,
    lineHeight: 15,
    textAlign: 'center',
    color: colors.defaultWhite,
  },
  headerText: {
    fontFamily: fonts.regular,
    fontSize: 14,
    lineHeight: 16,
    color: colors.lightBlack,
  },
  iconCircle: {
    borderColor: colors.regentBlue,
    borderWidth: 1,
    borderRadius: 50,
    height: 25,
    width: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
});
